// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DonkiNotifications: typeof import('./components/DonkiNotifications.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IBiGit: typeof import('~icons/bi/git')['default']
    'ICib:qgis': typeof import('~icons/cib/qgis')['default']
    IEmojioneGlobeShowingEuropeAfrica: typeof import('~icons/emojione/globe-showing-europe-africa')['default']
    IIcOutlineDarkMode: typeof import('~icons/ic/outline-dark-mode')['default']
    IIcOutlineWbSunny: typeof import('~icons/ic/outline-wb-sunny')['default']
    IIcRoundContentCopy: typeof import('~icons/ic/round-content-copy')['default']
    IIcTwotoneSailing: typeof import('~icons/ic/twotone-sailing')['default']
    'ILogos:tailwindcssIcon': typeof import('~icons/logos/tailwindcss-icon')['default']
    ILogosDockerIcon: typeof import('~icons/logos/docker-icon')['default']
    ILogosPython: typeof import('~icons/logos/python')['default']
    ILogosVue: typeof import('~icons/logos/vue')['default']
    IVscodeIconsFileTypeAws: typeof import('~icons/vscode-icons/file-type-aws')['default']
    IVscodeIconsFileTypeTypescriptOfficial: typeof import('~icons/vscode-icons/file-type-typescript-official')['default']
    PhotoGallery: typeof import('./components/PhotoGallery.vue')['default']
    ResponsiveGrid: typeof import('./components/ResponsiveGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
